function sma = getStateMatrix_laserPowerCalibration(triggerProfNum)
global S


sma = NewStateMatrix(); % Assemble state matrix

sma = SetGlobalTimer(sma, 'TimerID', 1, 'Duration', 60,...
    'OnsetDelay', 0, 'Channel', 'WavePlayer1', ...
    'OnMessage', triggerProfNum,'OffMessage',1,...
    'Loop', 0, 'SendGlobalTimerEvents', 0);


% Specify state matrix
sma = AddState(sma, 'Name', 'LaserOn', 'Timer', S.GUI.laserOnTime,...
    'StateChangeConditions', {'Tup', 'LaserOff'},...
    'OutputActions', {'GlobalTimerTrig', 1});

if S.GUI.laserOffTime == 0
    sma = AddState(sma, 'Name', 'LaserOff', 'Timer', 0.01,...
        'StateChangeConditions', {'Tup', 'exit'},...
        'OutputActions', {'GlobalTimerCancel', 1});
else
    sma = AddState(sma, 'Name', 'LaserOff', 'Timer', S.GUI.laserOffTime,...
        'StateChangeConditions', {'Tup', 'exit'},...
        'OutputActions', {'GlobalTimerCancel', 1});
end