% Test X-MBC2 Step Controller with soft code commands

function TestMotor()
global BpodSystem


sma = NewStateMatrix(); % Create a blank matrix to define the trial's finite state machine
   % add state for soft code to move target 
   % set up seperate function to call soft code
sma = AddState(sma, 'Name', 'MoveHome', ...
        'Timer', 1,...
        'StateChangeConditions', {'Tup', 'Delay'},...
        'OutputActions', {'SoftCode',1}); 
    
    %add state for delay
    sma = AddState(sma, 'Name', 'Delay', ...
        'Timer', 3,...
        'StateChangeConditions', {'Tup', 'exit'},...
        'OutputActions', []);
%     sma = AddState(sma, 'Name', 'MoveForward', ...
%         'Timer', 1,...
%         'StateChangeConditions', {'Tup', 'Delay'},...
%         'OutputActions', {'SoftCode',2}); 
    BpodSystem.SoftCodeHandlerFunction = 'TestMotor_handler';

    SendStateMachine(sma);
        RawEvents = RunStateMachine();
        